spring:
  data:
    rest:
      base-path: /api/v1
  datasource:
    url: jdbc:mysql://localhost:3306/db_project?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Crst#105243
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 9090